#!/bin/sh

set +x
set +e

# Run this command to do all the things
# Local requirements: commands for the following steps: 
#   baseline      -- distro images
#   dependencies  -- other haskell packages, from git
#   release       -- artifact copying and usage
# See sample implementation for each based on the included sample_* files

BRANCH=jenkins-clean

git clone -b $BRANCH https://github.com/anchor/docker-base.git 

. docker-base/base

build_init # TEST the sharing of environment variables

echo Name = $NAME
echo Options = $DOCKER_OPTS
echo Docker Registry = $DOCKER_REGISTRY
echo Version = $VERSION


initialize
baseline
dependencies
release
publish
#haddock
