#!/bin/sh

set +x
set +e

BRANCH=jenkins-clean

git clone -b $BRANCH https://github.com/anchor/docker-base.git 

. docker-base/base

build_init "$@" 

initialize
baseline
dependencies
release
publish
#haddock
