#!/bin/sh
set -x
set -e
pwd

#. ../docker-base/base

echo "dependencies - exporting, installing, cabal, etc"

# Git-based cabal source files
# Helper function: get github/anchor/<source>

export HOME=/src
#exec > /src/dependencies.log
#exec 2>&1

export PATH=/src/.cabal/bin:$PATH
cabal update

cd /src

get () {  
	git clone https://github.com/anchor/$1.git  
} 

get marquise
get chevalier-common
get sieste

cd /

find /src

cabal install -j \
	/src/marquise \
	/src/chevalier-common \
	/src/sieste 
