#!/bin/sh
set -x
set -e

export HOME=/src

# Git-based cabal source files
# Helper function: get github/anchor/<source>

export HOME=/src

exec > /src/dependencies.log
exec 2>&1

export PATH=/src/.cabal/bin:$PATH
cabal update

cd /src


echo "Get marquise, chevalier_common, sieste"
get marquise
get chevalier-common
get sieste

cd /

find /src

cabal install scotty

cabal install -j \
	/src/marquise \
	/src/chevalier-common \
	/src/sieste 
