#!/bin/sh
set -x
set -e
pwd

# Git-based cabal source files

export HOME=/src
export PATH=/src/.cabal/bin:$PATH

cabal update

cd /src

get () {
	get_branch=$2
	if [ -z $get_branch ]; then
		get_branch="master"
	fi
	git clone -b $get_branch https://github.com/anchor/$1.git
}

get marquise
get vaultaire-common
get chevalier-common
get sieste $GIT_BRANCH

cd /

find /src

cabal install -j \
	/src/vaultaire-common \
	/src/marquise \
	/src/chevalier-common \
	/src/sieste
